Repository kefranabg/bento-starter, pull requests merged in 2019-04, with the labels that each got.

#81 :sparkles: introduce offline for login page
  package-lock.json
  src/views/Login.vue
  tests/unit/views/Login.spec.js
Labels: :sparkles: enhancement, :white_check_mark: testing

#121 :lipstick: Align title and images in README
  README.md
Labels: :book: documentation, :lipstick: UI

#123 :memo: Add setup in readme
  README.md
  resources/firebase-web-btn.jpg
Labels: :book: documentation

#124 :speech_balloon: Fix typo: replace 'Optionnal' by 'Optional' in readme
  README.md
Labels: :book: documentation

#129 :fire: Remove readme setup section
  README.md
Labels: :book: documentation

#128 :speech_balloon: Fixed typo errors
  README.md
Labels: :book: documentation

#133 :speech_balloon: Adding slack link to readme
  README.md
Labels: :book: documentation
